Text_DreamEaterTeach:: @ 817E316
    .string "Yawn!\n"
    .string "I must have dozed off in the sun.\p"
    .string "I had this weird dream about\n"
    .string "a Drowzee eating my dream.\p"
    .string "And…\n"
    .string "I learned how to eat dreams…\p"
    .string "Oogh, this is too spooky!\p"
    .string "Let me teach it to a Pokémon so\n"
    .string "I can forget about it!$"

Text_DreamEaterDeclined:: @ 817E3E9
    .string "…Snore…$"

Text_DreamEaterWhichMon:: @ 817E3F1
    .string "Which Pokémon wants to learn\n"
    .string "Dream Eater?$"

Text_DreamEaterTaught:: @ 817E41B
    .string "…ZZZ…\n"
    .string "I…can't eat…anymore…$"

Text_DreamEaterReteach::
    .string "Even after teaching you Dream\n"
    .string "Eater, I still can't forget how to\l"
    .string "eat dreams!\p"
    .string "I'll keep teaching your Pokémon\n"
    .string "Dream Eater for ¥5000.$"

Text_DreamEaterReteach2::
    .string "Do you want me to teach\n"
    .string "a Pokémon Dream Eater?$"

Text_DreamEaterNotEnoughMoney::
    .string "The only thing spookier than\n"
    .string "Dream Eater is not having the\l"
    .string "¥5000 to learn it!\p"
    .string "I'll be happy to teach it to a\n"
    .string "Pokémon when you have enough money.$"

PewterCity_Text_ClefairyCameFromMoon:: @ 817E436
    .string "Clefairy came from the moon.\n"
    .string "That's what the rumor is.\p"
    .string "They appeared after Moon Stones\n"
    .string "fell on Mt. Moon.$"

PewterCity_Text_BrockOnlySeriousTrainerHere:: @ 817E49F
    .string "There aren't many serious Pokémon\n"
    .string "Trainers here.\p"
    .string "They're all like Bug Catchers,\n"
    .string "you know, just hobbyists.\p"
    .string "But Pewter Gym's Brock isn't like\n"
    .string "that, not one bit.$"

PewterCity_Text_DidYouCheckOutMuseum:: @ 817E53E
    .string "Did you check out the Museum?$"

PewterCity_Text_WerentThoseFossilsAmazing:: @ 817E55C
    .string "Weren't those fossils from Mt. Moon\n"
    .string "amazing?$"

PewterCity_Text_ReallyYouHaveToGo:: @ 817E589
    .string "Really?\n"
    .string "You absolutely have to go!$"

PewterCity_Text_ThisIsTheMuseum:: @ 817E5AC
    .string "This is it, the Museum.\p"
    .string "You have to pay to get in, but it's\n"
    .string "worth it. See you around!$"

PewterCity_Text_DoYouKnowWhatImDoing:: @ 817E602
    .string "Psssst!\n"
    .string "Do you know what I'm doing?$"

PewterCity_Text_ThatsRightItsHardWork:: @ 817E626
    .string "That's right!\n"
    .string "It's hard work!$"

PewterCity_Text_SprayingRepelToKeepWildMonsOut:: @ 817E644
    .string "I'm spraying Repel to keep wild\n"
    .string "Pokémon out of my garden!$"

PewterCity_Text_BrocksLookingForChallengersFollowMe:: @ 817E67E
    .string "You're a Trainer, right?\p"
    .string "Brock's looking for new\n"
    .string "challengers. Follow me!$"

PewterCity_Text_GoTakeOnBrock:: @ 817E6C7
    .string "If you have the right stuff,\n"
    .string "go take on Brock!$"

PewterCity_Text_TrainerTipsEarningEXP:: @ 817E6F6
    .string "Trainer Tips\p"
    .string "All Pokémon that appear in battle,\n"
    .string "however briefly, earn Exp Points.$"

PewterCity_Text_CallPoliceIfInfoOnThieves:: @ 817E748
    .string "Notice!\p"
    .string "Thieves have been stealing Pokémon\n"
    .string "fossils from Mt. Moon.\p"
    .string "Please call the Pewter Police if\n"
    .string "you have any information.$"

PewterCity_Text_MuseumOfScience:: @ 817E7C5
    .string "Pewter Museum of Science$"

PewterCity_Text_GymSign:: @ 817E7DE
    .string "Pewter City Pokémon Gym\n"
    .string "Leader: Brock\l"
    .string "The Rock-Solid Pokémon Trainer!$"

PewterCity_Text_CitySign:: @ 817E824
    .string "Pewter City\n"
    .string "A Stone Gray City$"

PewterCity_Text_OhPlayer:: @ 817E902
    .string "Oh, {PLAYER}{KUN}!$"

PewterCity_Text_AskedToDeliverThis:: @ 817E90C
    .string "I'm glad I caught up to you.\n"
    .string "I'm Prof. Oak's Aide.\p"
    .string "I've been asked to deliver this,\n"
    .string "so here you go.$"

PewterCity_Text_ReceivedRunningShoesFromAide:: @ 817E970
    .string "{PLAYER} received the\n"
    .string "letter from the Aide.$"

PewterCity_Text_SwitchedShoesWithRunningShoes:: @ 817E99D
    .string "{PLAYER} switched shoes with the\n"
    .string "Running Shoes.$"

PewterCity_Text_ExplainRunningShoes:: @ 817E9C7
    .string "Press the B Button to run.\n"
    .string "But only where there's room to run!$"

PewterCity_Text_MustBeGoingBackToLab:: @ 817EA06
    .string "Well, I must be going back to\n"
    .string "the Lab.\p"
    .string "Bye-bye!$"

PewterCity_Text_RunningShoesLetterFromMom:: @ 817EA36
    .string "{PLAYER} opened the letter…\p"
    .string "Dear {PLAYER},\p"
    .string "I see my beloved challenger\n"
    .string "left home with his Running Shoes.\p"
    .string "You can press the B Button to run,\n"
    .string "and the R Button can make it so\l"
    .string "you can run without holding B!\p"
    .string "Remember, I'll always cheer for\n"
    .string "you! Don't ever give up!\p"
    .string "From Mom$"

PewterCity_Text_RunningShoesLetterFromMomFemale:: @ 817EA36
    .string "{PLAYER} opened the letter…\p"
    .string "Dear {PLAYER},\p"
    .string "I see my beloved challenger\n"
    .string "left home with her Running Shoes.\p"
    .string "You can press the B Button to run,\n"
    .string "and the R Button can make it so\l"
    .string "you can run without holding B!\p"
    .string "Remember, I'll always cheer for\n"
    .string "you! Don't ever give up!\p"
    .string "From Mom$"
