SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMale:: @ 819AC60
    .string "{PLAYER}: Hi!\n"
    .string "Do you like Pokémon?\p"
    .string "{PLAYER}: Uh, no, I just asked you.\p"
    .string "{PLAYER}: Huh?\n"
    .string "You're strange!\p"
    .string "Copycat: Hmm? Quit mimicking?\n"
    .string "But, that's my favorite hobby!$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemale:: @ 819ACF1
    .string "{PLAYER}: Hi.\n"
    .string "You must like Pokémon.\p"
    .string "{PLAYER}: No, not me.\n"
    .string "I asked you.\p"
    .string "{PLAYER}: Pardon?\n"
    .string "You're weird!\l"
    .string " \l"
    .string "Copycat: Hmm? Quit mimicking?\l"
    .string "But that's my favorite hobby!$"

Text_MimicTeach:: @ 819AD85
    .string "Oh wow!\n"
    .string "A Poké Doll!\p"
    .string "For me?\n"
    .string "Thank you!\p"
    .string "You know what?\n"
    .string "I can teach the move Mimic.$"

Text_MimicDeclined:: @ 819ADD8
    .string "Don't you like Mimic?$"

Text_MimicWhichMon:: @ 819ADEE
    .string "I really love Mimic!\n"
    .string "Who's going to learn it?$"

Text_MimicTaughtMale:: @ 819AE1C
    .string "{PLAYER}: Hi!\n"
    .string "Thanks for earlier!\p"
    .string "{PLAYER}: Pardon?\p"
    .string "{PLAYER}: Is it that fun to mimic my\n"
    .string "every move?\p"
    .string "Copycat: You bet!\n"
    .string "It's a scream!$"

Text_MimicTaughtFemale:: @ 819AE90
    .string "{PLAYER}: Hi!\n"
    .string "Thanks for what you did for us.\p"
    .string "{PLAYER}: Pardon?\p"
    .string "{PLAYER}: Is it really that fun to\n"
    .string "copy what I say and do?\p"
    .string "Copycat: You bet!\n"
    .string "It's a scream!$"

Text_MimicReteach::
    .string "{PLAYER}: Hi!\n"
    .string "Could you teach us Mimic again?\p"
    .string "{PLAYER}: Pardon?\p"
    .string "{PLAYER}: Is it that fun to copy my\n"
    .string "every word?\p"
    .string "Copycat: Absolutely!\n"
    .string "It's a scream!\p"
    .string "I can reteach Mimic if you'll give\n"
    .string "me ¥5000 for more dolls!$"

Text_MimicReteach2::
    .string "Is that okay?\n"
    .string "Should I mimic teaching Mimic?$"

Text_MimicNotEnoughMoney::
    .string "{PLAYER}: ¥5000?\n"
    .string "But a Poké Doll only costs ¥1000!\p"
    .string "I don't have enough money for\n"
    .string "that right now…\p"
    .string "Copycat: I want to buy five\n"
    .string "Poké Dolls! So I need ¥5000!\p"
    .string "I'll mimic teaching Mimic to\n"
    .string "your Pokémon when you have it!$"

Text_MimicTaughtMale2::
    .string "{PLAYER}: Okay!\n"
    .string "Thanks for that!\p"
    .string "{PLAYER}: Pardon?\p"
    .string "{PLAYER}: Is it that fun to mimic my\n"
    .string "every move?\p"
    .string "Copycat: You bet!\n"
    .string "It's a scream!$"

Text_MimicTaughtFemale2:: @ 819AE90
    .string "{PLAYER}: Okay!\n"
    .string "Thanks for what you did for us.\p"
    .string "{PLAYER}: Pardon?\p"
    .string "{PLAYER}: Is it really that fun to\n"
    .string "copy what I say and do?\p"
    .string "Copycat: You bet!\n"
    .string "It's a scream!$"

SaffronCity_CopycatsHouse_2F_Text_Doduo:: @ 819B030
    .string "Doduo: Giiih!\p"
    .string "Pretty Mirror Look At Me,\n"r
    .string "See How Pretty I Can Be?$"

SaffronCity_CopycatsHouse_2F_Text_RareMonOnlyDoll:: @ 819B071
    .string "This is a rare Pokémon!\n"
    .string "Huh? It's only a doll!$"

SaffronCity_CopycatsHouse_2F_Text_MarioWearingABucket:: @ 819B0A0
    .string "A game with Mario wearing a bucket\n"
    .string "on his head!$"

SaffronCity_CopycatsHouse_2F_Text_MySecrets:: @ 819B0D0
    .string "…\p"
    .string "My Secrets!\p"
    .string "Skill: Mimicry!\n"
    .string "Hobby: Collecting dolls!\l"
    .string "Favorite Pokémon: Clefairy!$"

