
BattleTower_Outside_Text_199C6F:: @ 8199C6F
	.string "Battle Tower\n"
	.string "“Win it all and be the best!”$"

BattleTower_Outside_Text_199CA4:: @ 8199CA4
	.string "This is the Battle Tower.\p"
	.string "Trainers bring their best Pokémon\n"
	.string "for elimination-style matches.$"

BattleTower_Outside_Text_199E9C:: @ 8199E9C
	.string "I'm not leaving until I've beaten\n"
	.string "35 Trainers in a row!$"

BattleTower_Outside_Text_199ED4:: @ 8199ED4
	.string "Gee, there're a lot of\n"
	.string "tough-looking Trainers here.\l"
	.string "I'm not good enough to enter yet…$"
